name: React Deploy

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
    secrets:
      PERSONAL_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar build del artefacto
        uses: actions/download-artifact@v4
        with:
          name: build-${{ inputs.project }}
          path: dist
      
      - name: Deploy a gh-pages en deployments-repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: dist
          external_repository: KuboToel-Inc/deployments-repo
          publish_branch: gh-pages
